using Microsoft.EntityFrameworkCore.Migrations;

namespace TestePMWEB.Migrations
{
    public partial class sp_AtualizaCons_RFV : Migration
    {
		protected override void Up(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.Sql(@"
IF EXISTS(SELECT id FROM sysobjects WHERE name='p_AtualizaCons_RFV' AND xtype='P')
	DROP PROCEDURE [dbo].p_AtualizaCons_RFV
GO

CREATE PROCEDURE [dbo].p_AtualizaCons_RFV
AS
BEGIN
	Declare @TempoMedioRelacionamento decimal = (SELECT AVG(FLOOR(DATEDIFF(DAY, Pedidos.DATA_PEDIDO, GETDATE())/365.25)) as TEMPO_MEDIORELACIONAMENTO FROM Pedidos)
	CREATE TABLE #tempcli
	(
		ID_CLIENTE	int NOT NULL,
		DATA_ULTIMA_COMPRA	datetime2 NULL,
		ULTIMO_DEPTO_COMPRA	nvarchar(30) NULL,
		PARCELAMENTO_PREFER	nvarchar(20) NULL,
		MEIO_PAGAMENTO_PREFER	nvarchar(30) NULL,
		TICKET_MEDIO_ALL	decimal NULL,
		TICKET_MEDIO_12M	decimal NULL,
		FREQUENCIA_COMPRA_ALL	int NULL,
		FREQUENCIA_COMPRA_12M	int NULL,
		TIER_ATUAL	nvarchar(max) NULL
	)
	INSERT INTO #tempcli(ID_CLIENTE, DATA_ULTIMA_COMPRA, ULTIMO_DEPTO_COMPRA, PARCELAMENTO_PREFER, MEIO_PAGAMENTO_PREFER, TICKET_MEDIO_ALL
						, TICKET_MEDIO_12M, FREQUENCIA_COMPRA_ALL, FREQUENCIA_COMPRA_12M, TIER_ATUAL)	
		
		SELECT P.ID_CLIENTE
		, MAX(P.DATA_PEDIDO) AS DATA_ULTIMA_COMPRA
		, PD.DEPARTAMENTO AS ULTIMO_DEPTO_COMPRA
		, PP.PARCELAS AS PARCELAMENTO_PREFER
		, MP.MEIO_PAGAMENTO AS MEIO_PAGAMENTO_PREFER
		, (SUM(P.VALOR_UNITARIO)/COUNT(distinct(P.ID_PEDIDO))) AS TICKET_MEDIO_ALL
		, ISNULL(TP.TICKET_MEDIO, 0) as TICKET_MEDIO_12M
		, (DATEDIFF(D, MIN(P.DATA_PEDIDO), GETDATE())/ COUNT(distinct(P.ID_PEDIDO))) AS FREQUENCIA_COMPRA_ALL
		, ISNULL(TP.FREQUENCIA_COMPRA, 0) as FREQUENCIA_COMPRA_12M
		, dbo.fn_GetTier(SUM(P.VALOR_UNITARIO)) as TIER_ATUAL

		FROM Pedidos P
		LEFT JOIN Clientes C ON C.ID = P.ID_CLIENTE
		LEFT JOIN (SELECT COUNT(distinct(ID_PEDIDO)) as QTD_Pedidos
					, ID_CLIENTE
					, (SUM(VALOR_UNITARIO)/COUNT(distinct(ID_PEDIDO))) AS TICKET_MEDIO
					, (DATEDIFF(D, MIN(DATA_PEDIDO), GETDATE())/ COUNT(distinct(ID_PEDIDO))) AS FREQUENCIA_COMPRA
					FROM Pedidos
					WHERE DATA_PEDIDO >= DATEADD(MONTH,-12, GETDATE())
					GROUP BY ID_CLIENTE) AS TP ON tp.ID_CLIENTE = P.ID_CLIENTE
		LEFT JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY ID_CLIENTE ORDER BY COUNT(1)DESC) as number, MEIO_PAGAMENTO, ID_CLIENTE 
					FROM Pedidos
					GROUP BY MEIO_PAGAMENTO, ID_CLIENTE) as MP ON MP.ID_CLIENTE = P.ID_CLIENTE AND MP.number = 1
		LEFT JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY ID_CLIENTE ORDER BY COUNT(1)DESC) as number, PARCELAS, ID_CLIENTE 
					FROM Pedidos
					GROUP BY PARCELAS, ID_CLIENTE) as PP ON PP.ID_CLIENTE = P.ID_CLIENTE AND PP.number = 1
		
		LEFT JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY ID_CLIENTE ORDER BY MAX(DATA_PEDIDO) DESC) as number, DEPARTAMENTO, ID_CLIENTE 
					FROM Pedidos
					GROUP BY DEPARTAMENTO, ID_CLIENTE) as PD ON PD.ID_CLIENTE = P.ID_CLIENTE AND PD.number = 1
					
		GROUP BY  P.ID_CLIENTE, QTD_Pedidos, TP.TICKET_MEDIO, TP.FREQUENCIA_COMPRA, MP.MEIO_PAGAMENTO, PP.PARCELAS, PD.DEPARTAMENTO

		UPDATE Cons_RFV
			set Cons_RFV.DATA_ULTIMA_COMPRA = #tempcli.DATA_ULTIMA_COMPRA,
			Cons_RFV.ULTIMO_DEPTO_COMPRA = #tempcli.ULTIMO_DEPTO_COMPRA,
			Cons_RFV.PARCELAMENTO_PREFER = #tempcli.PARCELAMENTO_PREFER,
			Cons_RFV.MEIO_PAGAMENTO_PREFER = #tempcli.MEIO_PAGAMENTO_PREFER,
			Cons_RFV.TICKET_MEDIO_ALL = #tempcli.TICKET_MEDIO_ALL,
			Cons_RFV.TICKET_MEDIO_12M = #tempcli.TICKET_MEDIO_12M,
			Cons_RFV.FREQUENCIA_COMPRA_ALL = #tempcli.FREQUENCIA_COMPRA_ALL,
			Cons_RFV.FREQUENCIA_COMPRA_12M = #tempcli.FREQUENCIA_COMPRA_12M,
			Cons_RFV.TIER_ATUAL	= #tempcli.TIER_ATUAL
		FROM Cons_RFV INNER JOIN #tempcli on #tempcli.ID_CLIENTE = Cons_RFV.ID_CLIENTE
	DROP TABLE #tempcli
END
");
		}

		protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
