// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestePMWEB.Context;

namespace TestePMWEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210501030702_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestePMWEB.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CIDADE")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DATA_NASCIMENTO");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<short>("PERMISSAO_RECEBE_EMAIL");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.HasKey("ID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TestePMWEB.Models.Pedido", b =>
                {
                    b.Property<int>("ID_PEDIDO");

                    b.Property<int>("ID_CLIENTE");

                    b.Property<int>("ID_PRODUTO");

                    b.Property<int?>("CLIENTEID");

                    b.Property<DateTime>("DATA_PEDIDO");

                    b.Property<string>("DEPARTAMENTO")
                        .HasMaxLength(50);

                    b.Property<string>("MEIO_PAGAMENTO")
                        .HasMaxLength(50);

                    b.Property<int>("PARCELAS");

                    b.Property<int>("QUANTIDADE");

                    b.Property<string>("STATUS_PAGAMENTO")
                        .HasMaxLength(50);

                    b.Property<decimal>("VALOR_UNITARIO")
                        .HasColumnType("decimal(8, 3)");

                    b.HasKey("ID_PEDIDO", "ID_CLIENTE", "ID_PRODUTO");

                    b.HasAlternateKey("ID_CLIENTE", "ID_PEDIDO", "ID_PRODUTO");

                    b.HasIndex("CLIENTEID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TestePMWEB.Models.Pedido", b =>
                {
                    b.HasOne("TestePMWEB.Models.Cliente", "CLIENTE")
                        .WithMany("Pedidos")
                        .HasForeignKey("CLIENTEID");
                });
#pragma warning restore 612, 618
        }
    }
}
